import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.homePage}>
        <main className={styles.main}>
          <h1>Lorem Ipsum!</h1>
        </main>
        <aside>

        </aside>
      </div>
    </>
  )
}

export default Home
