import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSteam, faDiscord } from '@fortawesome/free-brands-svg-icons'
import { HomepageProps } from '../types'
import homePageProps from '../ssr'

export const getServerSideProps: GetServerSideProps = homePageProps;

const Home: NextPage<HomepageProps> = ({ steamMembers, discordMembers }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.homePage}>
        <main className={styles.main}>
          <div id={styles.header}>
            <div className={styles.icon}>
              <div className={styles.mask1}>
                <div className={styles.mask2}>
                  <img src="/orbit.png" />
                </div>
              </div>
            </div>

            <h1><i>Unturned Modded PVP</i></h1>
          </div>

          <h3>Join our Community:</h3>

          <section id={styles.groupInformation}>
            {/* Steam */}
            <a
              href='https://steamcommunity.com/groups/Orbit-SemiRP'
              target="_blank"
              rel="noreffer"
              className={styles.group}
            >
              <div className={styles.iconContainer}>
                <FontAwesomeIcon icon={faSteam} />
              </div>
              <span>{steamMembers}</span>
            </a>

            {/* Discord */}
            <a
              href='https://discord.gg/jqGxERcFEe'
              target="_blank"
              rel="noreffer"
              className={styles.group}
            >
              <div className={styles.iconContainer}>
                <FontAwesomeIcon icon={faDiscord} />
              </div>
              <span>{discordMembers}</span>
            </a>

            {/* Unturned Servers */}
            <a
              href='https://unturned-servers.net/server/299182/'
              target="_blank"
              rel="noreffer"
              className={styles.group}
            >
              <div className={styles.iconContainer}>
                <img src="unturned.png" />
              </div>
              <span>13/24</span>
            </a>
          </section>

          <p><b>Orbit Semi-RP</b> is a new upcoming server , with a custom map and soon custom mods . We plan on making a server where the players have a choice on whats going to be on our server and making the server easy to play and most importantly fun to play!</p>

          <ul>
            <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa neque voluptate modi fugit, impedit quaerat error maxime delectus? Quo doloribus dolores quas reprehenderit sunt non fugit voluptatum ipsum perferendis vitae!</li>
            <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minus maxime laboriosam culpa deleniti error non quam consequatur odio maiores quidem autem necessitatibus expedita ut id quas, inventore velit et.</li>
            <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam recusandae voluptate, commodi illum non veniam quaerat aperiam nesciunt magni, praesentium dolor sapiente cupiditate ex at, explicabo iusto. Eveniet, voluptatem voluptatum.</li>
            <li>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe cumque molestiae soluta optio voluptas, error, illum odit blanditiis eius id ab sequi delectus dolorem. Placeat ipsam assumenda architecto possimus nihil.</li>
          </ul>
        </main>
        <aside>
          <img src='/example.jpg' />
        </aside>
      </div>
    </>
  )
}

export default Home
