import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSteam, faDiscord } from '@fortawesome/free-brands-svg-icons'
import { HomepageProps } from '../types'

export const getServerSideProps: GetServerSideProps = async (): Promise<{ props: HomepageProps }> => {
  return {
    props: {
      steamMembers: "876",
      discordMembers: "1.23k"
    }
  }
}

const Home: NextPage<HomepageProps> = ({ steamMembers, discordMembers }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.homePage}>
        <main className={styles.main}>
          <h1>Lorem Ipsum!</h1>

          <section id={styles.groupInformation}>
            <div className={styles.group}>
              <div className={styles.iconContainer}>
                <FontAwesomeIcon icon={faSteam} />
              </div>
              <span>{steamMembers}</span>
            </div>

            <div className={styles.group}>
              <div className={styles.iconContainer}>
                <FontAwesomeIcon icon={faDiscord} />
              </div>
              <span>{discordMembers}</span>
            </div>
          </section>

          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, at quibusdam. Dicta, quam libero. Nam aperiam architecto magni porro dolorem quasi consequuntur omnis, sapiente quisquam eius fugiat repellendus illum quae?</p>

          <ul>
            <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa neque voluptate modi fugit, impedit quaerat error maxime delectus? Quo doloribus dolores quas reprehenderit sunt non fugit voluptatum ipsum perferendis vitae!</li>
            <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minus maxime laboriosam culpa deleniti error non quam consequatur odio maiores quidem autem necessitatibus expedita ut id quas, inventore velit et.</li>
            <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam recusandae voluptate, commodi illum non veniam quaerat aperiam nesciunt magni, praesentium dolor sapiente cupiditate ex at, explicabo iusto. Eveniet, voluptatem voluptatum.</li>
            <li>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe cumque molestiae soluta optio voluptas, error, illum odit blanditiis eius id ab sequi delectus dolorem. Placeat ipsam assumenda architecto possimus nihil.</li>
          </ul>
        </main>
        <aside>
          <img src='/example.jpg' />
        </aside>
      </div>
    </>
  )
}

export default Home
